config/routes.rb
Rails.application.routes.draw do
  get 'backoffice', to: 'backoffice/dashboard#index'
  namespace :backoffice do
    resources :categories, except: [:show, :destroy]
    resources :send_mail, only: [:edit, :create]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, except: [:show, :destroy]
    end

    resources :ad_detail, only: [:show]
    resources :categories, only: [:show]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: {sessions: 'members/sessions'}

  root 'site/home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
  after_action :verify_authorized, only: [:new, :destroy]

  def index
    @admins = policy_scope(Admin)
  end

  def new
    @admin = Admin.new
    authorize @admin
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to backoffice_admins_path, notice: "Administrador (#{@admin.email}) salvo com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def destroy
    authorize @admin
    admin_email = @admin.email
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "Administrador (#{admin_email}) excluído com sucesso!"
    else
      render :index
    end
  end

  def update
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].delete(:password)
      params[:admin].delete(:password_confirmation)
    end

    if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to backoffice_admins_path, notice: "Administrador (#{@admin.email}) alterado com sucesso!"
    else
      render :edit
    end
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def params_admin
    if @admin.blank?
      params.require(:admin).permit([:name, :email, :role, :password, :password_confirmation])
    else
      params.require(:admin).permit(policy(@admin).permited_attibutes)
    end
  end
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:edit, :update]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params_category)
    if @category.save
      redirect_to backoffice_categories_path, notice: "A categoria (#{@category.description}) salva com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(params_category)
      redirect_to backoffice_categories_path, notice: "A categoria (#{@category.description}) atualizada com sucesso!"
    else
      render :edit
    end
  end

  private

  def set_category
    @category = Category.friendly.find(params[:id])
  end

  def params_category
    params.require(:category).permit(:description)
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  def index
  end
end

app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController

  def edit
    @admin = Admin.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def create
    begin
      AdminMailer.send_message(current_admin,
                               params[:'recipient-text'],
                               params[:'subject-text'],
                               params['message-text']).deliver_now

      @notify_message = I18n.t('messages.email_delivered')
      @notify_flag = "success"
    rescue
      @notify_message = I18n.t('messages.email_not_delivered')
      @notify_flag = "error"
    end

    respond_to do |format|
      format.js
    end
  end

end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "backoffice"

  def pundit_user
    current_admin #current_user to Pundit Gem
  end
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  OptionsForRoles = Struct.new(:id, :description)

  def options_for_roles
    Admin.roles_i18n.map do |key, value|
      OptionsForRoles.new(key, value)
    end
  end
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/views/backoffice/admins/edit.html.erb
<%= render partial: "backoffice/admins/shared/form", locals: {form_action: "Editando Administrador"} %>

app/views/backoffice/admins/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Administradores</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                Listando Administradores
                <% if policy(@admins).new? %>
                    <%= link_to new_backoffice_admin_path,
                                class: "btn btn-info btn-circle pull-right",
                                style: "margin-top: -5px" do %>
                        <i class="fa fa-plus"></i>
                    <% end %>
                <% end %>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Nome</th>
                            <th>E-Mail</th>
                            <th colspan="2">Tipo de Acesso</th>
                        </tr>
                        </thead>
                        <tbody>
                        <% @admins.each do |admin| %>
                            <tr>
                                <td><%= admin.id %></td>
                                <td><%= admin.name %></td>
                                <td><%= admin.email %></td>
                                <td><%= admin.role_i18n %></td>
                                <td>
                                    <%= link_to edit_backoffice_send_mail_path(admin),  class: "btn btn-info btn-circle", remote: true do %>
                                        <i class="fa fa-envelope-o"></i>
                                    <% end %>
                                    <%= link_to edit_backoffice_admin_path(admin),  class: "btn btn-primary btn-circle" do %>
                                        <i class="fa fa-edit"></i>
                                    <% end %>
                                    <% if ((current_admin.id != admin.id) && (policy(@admins).destroy?)) %>
                                        <%= link_to backoffice_admin_path(admin), method: :delete,
                                                    data: {confirm: t('messages.confirm_with', item: admin.name)},
                                                    class: "btn btn-danger btn-circle" do %>
                                            <i class="fa fa-minus"></i>
                                        <% end %>
                                    <% end %>
                                </td>
                            </tr>
                        <% end %>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
</div>

<%= render partial: "backoffice/admins/shared/send_mail" %>

app/views/backoffice/admins/new.html.erb
<%= render partial: "backoffice/admins/shared/form", locals: {form_action: "Novo Administrador"} %>