config/routes.rb
Rails.application.routes.draw do
  get 'backoffice', to: 'backoffice/dashboard#index'
  namespace :backoffice do
    resources :categories, except: [:show, :destroy]
    resources :send_mail, only: [:edit, :create]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, except: [:show, :destroy]
    end

    resources :ad_detail, only: [:show]
    resources :categories, only: [:show]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: {sessions: 'members/sessions'}

  root 'site/home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :member
  belongs_to :category, counter_cache: true

  # Active Storage
  has_one_attached :picture
  has_many :comments

  # RubyMoney - Money-Rails
  monetize :price_cents

  # Validates
  validates :title, :description, :category, :price, presence: true
  validates :price, numericality: { greater_than: 0}

  # Scopes
  scope :descending_order, -> (quantity = 9) {limit(quantity).order(created_at: :desc)}
  scope :member_ads, -> (member) {where(member: member)}
  scope :by_category, -> (id) {where(category: id)}
  scope :search, -> (term) {where("lower(title) LIKE ?", "%#{term.downcase}%")}
end

app/models/admin.rb
class Admin < ApplicationRecord
  enum role: [:full_access, :restricted_access]

  scope :with_full_access, -> { where(role: 0) }
  scope :with_restricted_access, -> { where(role: 1) }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  # FriendlyId Configuration
  include FriendlyId
  friendly_id :description, use: :slugged

  # Associations
  has_many :ads

  # Validations
  validates_presence_of(:description)
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :ad
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :ads
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # Pundit Gem
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # set layout
  layout :layout_by_resource

  private

  # Pundit Gem
  def user_not_authorized
    flash[:alert] = t("messages.not_authorized")
    redirect_to(request.referrer || root_path)
  end

  # set layout
  def layout_by_resource
    if devise_controller? && resource_name == :admin
      "backoffice_devise"
    elsif devise_controller? && resource_name == :member
      "site_devise"
    else
      "application"
    end
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "backoffice"

  def pundit_user
    current_admin #current_user to Pundit Gem
  end
end

app/controllers/site/home_controller.rb
class Site::HomeController < SiteController
  def index
    @categories = Category.order(:description)
    @ads = Ad.descending_order
  end
end

app/controllers/site/profile_controller.rb
class Site::ProfileController < SiteController
  layout "profile"
end

app/controllers/site/search_controller.rb
class Site::SearchController < SiteController
  def ads
    @ads = Ad.search(params[:q])
    @categories = Category.all
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  #before_action :authenticate_member!
  layout "site"

  #def pundit_user
  #  current_member #current_user to Pundit Gem
  #end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def md_to_html(text)
    options = {
        filter_html: true,
        link_attributes: {
            rel: "nofollow",
            target: "_blank"
        }
    }

    extensions = {
        space_after_headers: true,
        autolink: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  OptionsForRoles = Struct.new(:id, :description)

  def options_for_roles
    Admin.roles_i18n.map do |key, value|
      OptionsForRoles.new(key, value)
    end
  end
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/helpers/site/ad_detail_helper.rb
module Site::AdDetailHelper
end

app/helpers/site/categories_helper.rb
module Site::CategoriesHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/views/backoffice/admins/shared/_form.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Administradores</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-8">
        <% if @admin.errors.any? %>
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <ul>
                    <% @admin.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
        <div class="panel panel-default">
            <div class="panel-heading">
                <%= form_action %>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <%= form_for([:backoffice, @admin]) do |f| %>
                        <div class="form-group">
                            <label>Nome</label>
                            <%= f.text_field :name, class: "form-control", placeholder: "Nome do administrador" %>
                        </div>
                        <div class="form-group">
                            <label>E-mail</label>
                            <%= f.text_field :email, class: "form-control", placeholder: "E-mail" %>
                        </div>
                        <% if policy(@admin).edit? %>
                            <div class="form-group">
                                <label>Tipo de Acesso</label>
                                <%= f.collection_radio_buttons :role, options_for_roles, :id, :description do |b| %>
                                    <div class="radio">
                                        <label>
                                            <%= b.label {b.radio_button + b.text} %>
                                        </label>
                                    </div>
                                <% end %>
                            </div>
                        <% end %>
                        <div class="form-group">
                            <label>Senha</label>
                            <%= f.password_field :password, class: "form-control", placeholder: "Senha" %>
                        </div>
                        <div class="form-group">
                            <label>Repita a senha</label>
                            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Repita a senha" %>
                        </div>
                        <button type="submit" class="btn btn-default">Salvar</button>
                    <% end %>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
</div>
<!-- /.row -->

app/views/backoffice/admins/shared/_send_mail.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel"><%= t('labels.new_message') %></h4>
            </div>
            <div class="modal-body">
                <%= form_tag(backoffice_send_mail_index_path, remote: true) do %>
                    <div class="form-group">
                        <label for="recipient-text" class="control-label"><%= t('labels.recipient') %></label>
                        <%= text_field_tag(:'recipient-text', nil, class: "form-control", readonly: "readonly") %>
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="control-label"><%= t('labels.subject') %></label>
                        <%= text_field_tag(:'subject-text', nil, class: "form-control", required: "required") %>
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="control-label"><%= t('labels.message') %></label>
                        <%= text_area_tag(:'message-text', nil, class: "form-control", required: "required") %>
                    </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.close') %></button>
                        <%= submit_tag t('buttons.send_message'), class: "btn btn-primary" %>
                    </div>
                <% end %>
                </div>
    </div>
</div>

app/views/layouts/shared/_notifications.html.erb
<% if notice %>
    <%= javascript_tag "$.notify( { message: '#{notice}'}, { type: 'success', placement: { from: 'top', align: 'center' }});" %>
<% end %>

<% if alert %>
    <%= javascript_tag "$.notify( { message: '#{alert}'}, { type: 'danger', placement: { from: 'top', align: 'center' }});" %>
<% end %>